README.md, sonar-orchestrator/pom.xml, sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/MavenBuildExecutor.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/config/Configuration.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/config/FileSystem.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/URLLocator.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/MavenBuildExecutorTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/MavenBuildTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/config/FileSystemTest.java, sonar-orchestrator/src/test/resources/com/sonar/orchestrator/config/FileSystemTest/maven/bin/fake.cmd
Hi,
Features proposal :
- Maven custom installation support
- Proxy authentication support
**Maven custom installation**
- Maven binary used support (for ``mvnDebug.cmd`` or BAT with special context initialization)
- _(Space support in Maven path (windows) --> done by @henryju in commit_ ac5e199612fd76953c56e7d35657983c2e56be4b)
**Proxy authentication support**
- Same user/password for ``http`` & ``https``
Fix unit test for pass in this context.
Best regards
=> Maven custom installation & proxy authentication support

orchestrator.properties, pom.xml, sonar-orchestrator-osgi/pom.xml, sonar-orchestrator/src/main/java/com/sonar/orchestrator/OrchestratorBuilder.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/container/Server.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/container/SonarDistribution.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerZipFinder.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderLongTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/container/ServerTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/container/SonarDistributionTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerZipFinderTest.java
- bring back web context
- drop version aliases LTS_OR_OLDEST_COMPATIBLE and OLDEST_COMPATIBLE
- ability to install local ZIP of SonarQube, without requesting update center
=> Various improvements

echo/pom.xml, pom.xml, sonar-orchestrator-osgi/pom.xml, sonar-orchestrator/pom.xml
Version was not bumped after previous release, need to update it, before technical release
=> Prepare for next development iteration

sonar-orchestrator/src/main/java/com/sonar/orchestrator/OrchestratorBuilder.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/container/SonarDistribution.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/container/SonarDistributionTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java
See https://github.com/SonarSource/sonar-enterprise/pull/3883 and https://jira.sonarsource.com/browse/MMF-2303.
=> ORCH-454 Disable sonar.forceRedirectOnDefaultAdminCredentials by default

sonar-orchestrator/src/main/java/com/sonar/orchestrator/OrchestratorBuilder.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/util/System2.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderTest.java
Do you mind checking this out, Jacek?
I've tested it locally with an IT.
=> ORCH-459 Enable remote debug of CE and Web processes

pom.xml, sonar-orchestrator/src/main/java/com/sonar/orchestrator/db/DatabaseClient.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/db/DefaultDatabase.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/db/PostgreSql.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/db/DatabaseClientTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/db/PostgreSqlTest.java
=> ORCH-468 Support postgresql v15

.cirrus.star, .cirrus.yml, .github/workflows/release.yml
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
=> BUILD-2143: vault migration

.cirrus.star, .cirrus.yml
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
=> BUILD-2273 Migrate to CirrusCI on AWS

pom.xml
Upgrading to latest pom parent, to fix the release issue we face currently.
=> NO-JIRA upgrade pom parent

.cirrus.yml
Ticket: https://sonarsource.atlassian.net/browse/ORCH-484
=> ORCH-484 Migrate away of GCP promote function

echo/pom.xml, pom.xml, sonar-orchestrator-junit4/pom.xml, sonar-orchestrator-junit5/pom.xml, sonar-orchestrator/pom.xml
Notes: this was forgotten after the last release, so it's needed to release 4.7 and after I release it I'll make the same to prepare 4.8 iteration.
=> NOJIRA Prepare 4.7 iteration

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[ORCH-500](https://sonarsource.atlassian.net/browse/ORCH-500)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last line! …
=> ORCH-500 Add Jira integration

sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/SonarScanner.java
[ORCH-503](https://sonarsource.atlassian.net/browse/ORCH-503)
[ORCH-503]: https://sonarsource.atlassian.net/browse/ORCH-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-503 Update Scanner CLI to 7.0.0

sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderTest.java
[ORCH-507](https://sonarsource.atlassian.net/browse/ORCH-507)
[ORCH-507]: https://sonarsource.atlassian.net/browse/ORCH-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-507 Upgrade latest version for builder test

sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/SonarScanner.java
[ORCH-503](https://sonarsource.atlassian.net/browse/ORCH-503)
[ORCH-503]: https://sonarsource.atlassian.net/browse/ORCH-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-503 Update embedded Scanner CLI to 7.0.2

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerCommandLineFactory.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerCommandLineFactoryTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java
[ORCH-505](https://sonarsource.atlassian.net/browse/ORCH-505)
[ORCH-505]: https://sonarsource.atlassian.net/browse/ORCH-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-505 Allow IPv6 support

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerCommandLineFactory.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerCommandLineFactoryTest.java
=> ORCH-506 increase xmx

echo/pom.xml, pom.xml, sonar-orchestrator-junit4/pom.xml, sonar-orchestrator-junit5/pom.xml, sonar-orchestrator/pom.xml
[ORCH-508](https://sonarsource.atlassian.net/browse/ORCH-508)
=> ORCH-508 Bump version to 5.3

.github/workflows/PullRequestClosed.yml
[ORCH-511](https://sonarsource.atlassian.net/browse/ORCH-511)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[ORCH-511]: https://sonarsource.atlassian.net/browse/ORCH-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-511 Autoclose issues created by Jira integration

pom.xml, sonar-orchestrator/pom.xml
=> fixing build

sonar-orchestrator/pom.xml
=> ORCH-513 fixing coverage issue

.github/workflows/release.yml
[PREQ-405](https://sonarsource.atlassian.net/browse/PREQ-405)
[PREQ-405]: https://sonarsource.atlassian.net/browse/PREQ-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PREQ-405 fix release action

echo/pom.xml, pom.xml, sonar-orchestrator-junit4/pom.xml, sonar-orchestrator-junit5/pom.xml, sonar-orchestrator/pom.xml
=> NO-JIRA bump version after release

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java
[ORCH-497](https://sonarsource.atlassian.net/browse/ORCH-497)
Good code
[ORCH-497]: https://sonarsource.atlassian.net/browse/ORCH-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-497 use staging url as default

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java
[ORCH-518](https://sonarsource.atlassian.net/browse/ORCH-518)
Part of 
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
[ORCH-518]: …
=> ORCH-518 Avoid calling fix suggestion prod endpoints in orchestrator

.cirrus.yml, .mvn/develocity.xml, .mvn/extensions.xml
[SONAR-24808](https://sonarsource.atlassian.net/browse/SONAR-24808)
[SONAR-24808]: https://sonarsource.atlassian.net/browse/SONAR-24808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24808 onboard orchestrator on develocity

echo/pom.xml, pom.xml, sonar-orchestrator-junit4/pom.xml, sonar-orchestrator-junit5/pom.xml, sonar-orchestrator/pom.xml
[ORCH-521](https://sonarsource.atlassian.net/browse/ORCH-521)
[ORCH-521]: https://sonarsource.atlassian.net/browse/ORCH-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-521 NO-JIRA Bump version to 5.6

sonar-orchestrator/src/main/java/com/sonar/orchestrator/util/Command.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/util/CommandExecutorTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/util/CommandTest.java
[ORCH-525](https://sonarsource.atlassian.net/browse/ORCH-525)
[ORCH-525]: https://sonarsource.atlassian.net/browse/ORCH-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-525 Add Command.setEnvironment

echo/pom.xml, pom.xml, sonar-orchestrator-junit4/pom.xml, sonar-orchestrator-junit5/pom.xml, sonar-orchestrator/pom.xml
[ORCH-524](https://sonarsource.atlassian.net/browse/ORCH-524)
[ORCH-524]: https://sonarsource.atlassian.net/browse/ORCH-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-524 Bump version to 5.6.1

echo/pom.xml, pom.xml, sonar-orchestrator-junit4/pom.xml, sonar-orchestrator-junit5/pom.xml, sonar-orchestrator/pom.xml
[ORCH-527](https://sonarsource.atlassian.net/browse/ORCH-527)
[ORCH-527]: https://sonarsource.atlassian.net/browse/ORCH-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ORCH-527 Bump version to 5.6.2

sonar-orchestrator/pom.xml, sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/SynchronousAnalyzerTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/config/LicensesTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/container/ServerTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/http/HttpCallTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/DefaultArtifactoryTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/GitHubImplTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/MavenArtifactoryTest.java, sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/URLLocatorTest.java
https://square.github.io/okhttp/changelogs/changelog/#version-510
=> ORCH-538 Update okhttp to 5.1

sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/Build.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/BuildResult.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/container/Server.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/FileLocation.java, sonar-orchestrator/src/main/java/com/sonar/orchestrator/util/MavenVersionResolver.java
=> NO-JIRA Fixing quality gate
