SonarSource/orchestrator

README.md
sonar-orchestrator/pom.xml
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/URLLocator.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/URLLocatorTest.java

Following #1 (Proxy support : unit tests).
NB: 
* SSL not supported, focus on proxy authentication
* Using Jetty version included in project, not upgraded to last like [sonar-scanner-api:ProxyTest](https://github.com/SonarSource/sonar-scanner-api/blob/master/its/it-tests/src/test/java/com/sonar/scanner/api/it/ProxyTest.java)
* okhttp upgraded to v3.5.0 (required for proxy test, see [#2525](https://github.com/square/okhttp/issues/2525))

Unit tests for proxy support

---

sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/MavenBuildExecutorTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/SonarScannerExecutorTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/config/ConfigurationTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/FileLocationTest.java

Fix some UT for managing directories containing some space (mainly orchestrator sources location), like :
```
java.lang.IllegalStateException: Please check the system property 'orchestrator.it_sources' or the env variable 'SONAR_IT_SOURCES'. Directory does not exist: C:\Users\Firstname%20Lastname\git\orchestrator\sonar-orchestrator\target\test-classes\com\sonar\orchestrator\locator\FileLocationTest
```

Fix UT on Windows when directories contain some space

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/container/Server.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/container/ServerTest.java

- use "project" param instead of "key" when calling api/projects/create
- in Orchestrator#associateProjectToQualityProfile, when using api/qualityprofiles/add_project : 
* Parameter "projectKey" has been replaced by "project" 
* Parameter "profileName" has been replaced by "qualityProfile" 
Jira Ticket: [ORCH-439](https://jira.sonarsource.com/browse/ORCH-439)

ORCH-439 - remove usage of deprecated webservice

---

sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderTest.java

Test was trying to install DEV version of sonar-python which is not supported in 6.7. Fixed it by bumping version to 7.9

Fix UT dependent on plugin

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/OrchestratorBuilderTest.java

This change will treat bundled plugin locations are "normal" plugin locations when the SQ version being started is pre 8.5.

Install bundled plugins as normal plugins if bundled plugins are not supported

---

.github/workflows/release.yml

The release github action is failing (see https://github.com/SonarSource/orchestrator/actions/runs/4435189877/workflow), I copied the workflow file from another recently released project.

NO-JIRA Update gh workflow release file

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/db/H2.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java

Notes for the reviewer:
- I didn't add any complexity to log whether or not the port comes from config, or is allocated using `getNextAvailablePort()`. We can easily figure out if the port comes from config or not, so these logs are helpful as they are, no need for more logic.
- I didn't test (assert) those logs because we don't have a `LogTester` here or equivalent. To me, just for logs, this is ok.

ORCH-477 Log allocated ports to help debugging

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java

The purpose is to give a determinist port to `sonar.es.port` (ElastiSearch TCP port), as we only did for `sonar.search.port` (HTTP port).
I remove usage of `setIfNotPresent()` for ES properties, as 1/ they are not set elsewhere and 2/ it's not possible to configure them from _orchestrator.properties_ file, so essentially they can't be present.

ORCH-478 Configure ES TCP port to avoid random pick

---

.github/workflows/release.yml

Notes for the reviewer:
- The purpose is to exclude the echo module from the release download artifact. The new option used had been suggested by the RE team in https://sonarsource.atlassian.net/browse/BUILD-3949

ORCH-473 Exclude the echo module from the release

---

.github/workflows/release.yml

Notes for the reviewer:
- `downloadExclusions` is the property for the already existing action `maven-central`, but it was not a new parameter for the `release` action itself that we are using here
- The RE team added an property to drive this setting from the `release` action directly, in PR https://github.com/SonarSource/gh-action_release/pull/98/files
- Also they released a new version of the release action

NOJIRA Update property to exclude the echo module from the release

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java

For the reviewer:
- cluster host properties should be set outside of orchestrator, so now we fail if they are not
- there was a weird logic (and badly named) with the `loadPort()` function so I reworked this to make the intention clearer (setting a port if none is given)
- this version had been used in a full sonar-enterprise QA loop on PR https://github.com/SonarSource/sonar-enterprise/pull/9912, including HA tasks

ORCH-480 Do not override HOST properties

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/ServerInstaller.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/config/LicensesTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/ServerInstallerTest.java

The goal of this PR is to remove all logic associated to the support of old (unsupported) version of SQ. It was more significant than I thought:
- copying plugin in `preparePlugins()` does not have to care about <8.5 anymore
- `copyExternalPlugins()` was also putting the old license plugin for commercial editions. We don't need this 7.2+
- `sonar.forceAuthentication` and `sonar.forceRedirectOnDefaultAdminCredentials` had special treatment for <8.8 versions in `configureProperties()`, not needed anymore
- the DCE configuration was different before 8.6. I removed the logic around `useNewDCESearchClusterConfiguration()` and refactored it to a simple `isClusterEnabled()` logic
After these changes, quite some tests had to be dropped or refactored. I took the opportunity to update SQ versions …

ORCH-480 Remove support for old versions of SonarQube

---

sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/dotnet/scanner/package-info.java

Sets the `ParametersAreNonnullByDefault` package level annotation.

Add package-info.java for dotnet scanner

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/ScannerForMSBuild.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/build/dotnet/scanner/package-info.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/GitHub.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/GitHubImpl.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/version/Version.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/build/ScannerForMSBuildTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/GitHubImplTest.java

This adds the option for the `SonarScanner for .NET` consumers to always download the latest version.
It works by calling the GitHub [latest release](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release) API and forwarding the result to the existing implementation.
The latest release query: https://api.github.com/repos/SonarSource/sonar-scanner-msbuild/releases/latest

Add support for LATEST_RELEASE

---

pom.xml

In ec7d93bbbf8c8a3837422b6dae301ce73c13ef1e the version of `logback` was updated from `1.2.x` to `1.3.x`. This leads to logging not working correctly anymore:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
```
The reason seems to be that `slf4j` has to be updated along. Logback `1.3.x` seems to require slf4j `2.x`. I didn't really find an official statement about this in the changelog, but see https://github.com/swagger-api/swagger-codegen/issues/12135#issuecomment-1625513809 and https://logback.qos.ch/download.html stating `The current actively developed version of logback supporting Java EE (java.* namespace) is 1.3.14. It requires SLF4J version 2.0.7 and JDK 8.`

NO-JIRA Update slf4j version

---

README.md
sonar-orchestrator/pom.xml
sonar-orchestrator/src/main/java/com/sonar/orchestrator/config/Configuration.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/Artifactory.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/ArtifactoryFactory.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/DefaultArtifactory.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/MavenArtifactory.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/MavenRepositoryVersion.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/util/MavenVersionResolver.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/ArtifactoryFactoryTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/DefaultArtifactoryTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/MavenArtifactoryTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/MavenRepositoryVersionTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/util/MavenVersionResolverTest.java

Currently, Orchestrator supports all types of literals to retrieve artifacts, such as
- DEV
- DOGFOOD
- LATEST_RELEASE
- The above three can contain [<version>], i.e. DEV[10.1]
- Hardcoded version i.e. 10.3
With disabling JFrog anonymous usage/authentication, other open source projects that are using Orchestrator can no longer download artifacts from JFrog - unless they specify credentials
The new approach is as follows:
- if `orchestrator.artifactory.url` remains empty, default `https://repox.jfrog.io/repox` is used
- Setting `orchestrator.artifactory.url` to anything else **will be assumed to be a maven repository**
So, for testing, setting `orchestrator.artifactory.url` to `https://repo1.maven.org/maven2`, I tested using a few literals and/or versions (for SQ artifacts):
**1) …

ORCH-487 Add support for downloading artifacts without repox

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/ArtifactoryFactory.java

As it turns out, not every team/squad in the company uses the default JFrog URL `https://repox.jfrog.io/repox`, rather they use `https://repox.jfrog.io/atrifactory`. Therefore, as per the logic in the [changes](https://github.com/SonarSource/orchestrator/pull/189) introduced to allow external users to default to a maven repository, the strictness of expecting the default URL to start with `https://repox.jfrog.io/repox` to utilize JFrog is flawed.
Let us make it less stringent. If the URL starts with `https://repox.jfrog.io`, default to Repox, otherwise it will be assumed to be a Maven repository.

ORCH-490 Make default artifactory URL check less stringent

---

README.md
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/DefaultArtifactory.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/MavenArtifactory.java
sonar-orchestrator/src/main/java/com/sonar/orchestrator/server/PackagingResolver.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/DefaultArtifactoryTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/MavenArtifactoryTest.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/server/PackagingResolverTest.java

With this logic in place calculation of the Maven Group ID and Artifact ID is dependent on the Edition being passed.
In the past everything was hardcoded to `org.sonarsource.sonarqube:sonar-application`.
With this new logic when passing DEV and DEVELOPER edition the downloaded version is:
When passing DEV and Community edition the downloaded version is:

ORCH-498 Get the correct DEV edition of SonarQube Community Build and Server

---

sonar-orchestrator/src/main/java/com/sonar/orchestrator/locator/MavenRepositoryVersion.java
sonar-orchestrator/src/test/java/com/sonar/orchestrator/locator/MavenRepositoryVersionTest.java

Hello,
I am using orchestrator in the integration tests of the [spotbugs/sonar-findbugs](https://github.com/spotbugs/sonar-findbugs) project.
In the recent builds it looks like orchestrator is now failing to parse the content of https://repo1.maven.org/maven2/org/sonarsource/sonarqube/sonar-application/maven-metadata.xml
The error is:
```
java.lang.ExceptionInInitializerError
at org.sonar.plugins.findbugs.it.FindSecBugsIT.<clinit>(FindSecBugsIT.java:23)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at java.base/java.util.Optional.orElseGet(Optional.java:364)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at …
```

ORCH-523 Add missing modelVersion to the maven repo version object

---

.github/workflows/PullRequestClosed.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/slack_notify.yml

[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …

BUILD-8875: Migrate to standardized GitHub runner names
